---
HOSTS:
  centos6-64-1:
    platform: el-6-x86_64
    hypervisor: docker
    image: centos:6
    docker_preserve_image: true
    docker_cmd: '["/usr/sbin/init"]'
    docker_image_commands:
      - 'rm -rf /var/run/network/*'
      - 'yum install -y crontabs initscripts iproute openssl sysvinit-tools tar wget which'
      - 'rm /etc/init/tty.conf'
CONFIG:
  trace_limit: 200
  masterless: true
...
