---
HOSTS:
  centos7-64-1:
    platform: fedora-24-x86_64
    hypervisor: docker
    image: fedora:24
    docker_preserve_image: true
    docker_cmd: '["/usr/sbin/init"]'
    docker_image_commands:
      - 'yum install -y crontabs initscripts iproute openssl sysvinit-tools tar wget which ss'
      - 'systemctl mask getty@tty1.service'
CONFIG:
  trace_limit: 200
  masterless: true
...
