fixtures:
  repositories:
    apt:
      repo: 'git://github.com/puppetlabs/puppetlabs-apt'
      ref: '2.3.0'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
      ref: '4.14.0'
    yum:
      repo: 'git://github.com/voxpupuli/puppet-yum'
      ref: 'v0.9.15'
    debconf:
      repo: 'git://github.com/smoeding/puppet-debconf'
      ref: 'v1.0.1'
  symlinks:
    timezone: "#{source_dir}"
