fixtures:
  repositories:
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt.git'
      ref: '2.3.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.14.0'
    yum:
      repo: 'https://github.com/voxpupuli/puppet-yum.git'
      ref: 'v0.9.15'
    debconf:
      repo: 'https://github.com/smoeding/puppet-debconf.git'
      ref: 'v2.0.0'
  symlinks:
    timezone: "#{source_dir}"
